### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np
arr = np.random.randint(1, 51, size=10)

media = np.mean(arr)
desvio_padrao = np.std(arr)

print(arr)
print(media)
print(desvio_padrao)

[29  3 24 26  4  6 42 44 11 37]
22.6
14.954597955144097


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
import numpy as np

arr = np.random.rand(10)
arr[arr <= 0.5] = np.sqrt(arr[arr <= 0.5])
print(arr)

[0.07785926 0.15691044 0.89700254 0.58603133 0.3971558  0.89074563
 0.6054737  0.39748184 0.22124446 0.79298181]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
import numpy as np

matriz = np.random.rand(3, 3, 3)

valor_max = np.amax(matriz, axis = 1)

print('Matriz:\n',matriz)
print('Valor Máximo:\n',valor_max)


Matriz:
 [[[0.90655007 0.92271499 0.01371424]
  [0.24766726 0.84530305 0.20272388]
  [0.83291848 0.29743184 0.44636978]]

 [[0.4885898  0.29834459 0.78708323]
  [0.69373354 0.0845354  0.53098144]
  [0.43602434 0.75521453 0.56245922]]

 [[0.26582069 0.57166272 0.14080069]
  [0.95482699 0.81446747 0.47785552]
  [0.41286781 0.34673883 0.50460948]]]
Valor Máximo:
 [[0.90655007 0.92271499 0.44636978]
 [0.69373354 0.75521453 0.78708323]
 [0.95482699 0.81446747 0.50460948]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
import numpy as np

matriz = np.random.rand(5, 5)

media = np.mean(matriz, axis=1)

matriz_linha_media = matriz - media.reshape((-1,1))

print("Matriz:\n", matriz)
print("Média Linhas:\n", media)
print("Matriz Subtração:\n", matriz_linha_media)

Matriz:
 [[0.88568391 0.88708471 0.77111768 0.21922464 0.9923545 ]
 [0.66713281 0.9312682  0.25446608 0.52207282 0.7921721 ]
 [0.53495644 0.82247924 0.66679136 0.86960262 0.62253458]
 [0.93189671 0.22875559 0.8966856  0.39501626 0.32314469]
 [0.59628102 0.64382176 0.13614724 0.90454244 0.43164329]]
Média Linhas:
 [0.75109309 0.6334224  0.70327285 0.55509977 0.54248715]
Matriz Subtração:
 [[ 0.13459082  0.13599162  0.02002459 -0.53186845  0.24126141]
 [ 0.03371041  0.2978458  -0.37895632 -0.11134958  0.1587497 ]
 [-0.16831641  0.11920639 -0.03648149  0.16632977 -0.08073826]
 [ 0.37679694 -0.32634418  0.34158583 -0.16008351 -0.23195508]
 [ 0.05379387  0.10133461 -0.40633991  0.36205529 -0.11084386]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
import numpy as np

matriz = np.random.rand(4, 4)

diagonal_prin = np.diagonal(matriz)
diagonal_sec = np.diagonal(matriz[::-1])
media = np.mean(arr)
desvio_padrao = np.std(arr)


print('Matriz: ',matriz)
print('Diagonal Principal: ',diagonal_prin)
print('Diagonal Secundária: ',diagonal_sec)
print('Média:',media)
print('Desvio Padrão:',desvio_padrao)


Matriz:  [[0.76494283 0.71997178 0.22427994 0.38106242]
 [0.0562606  0.86721914 0.40733151 0.99763253]
 [0.82166846 0.97939737 0.84247198 0.67633931]
 [0.89660264 0.12422134 0.54917614 0.70040082]]
Diagonal Principal:  [0.76494283 0.86721914 0.84247198 0.70040082]
Diagonal Secundária:  [0.89660264 0.97939737 0.40733151 0.38106242]
Média: 22.6
Desvio Padrão: 14.954597955144097
